name: warm_alarm_ios
description: iOS implementation of the warm_alarm plugin
version: 0.1.0+1

homepage: https://github.com/AndrewDongminYoo/warm_alarm
repository: https://github.com/AndrewDongminYoo/warm_alarm
issue_tracker: https://github.com/AndrewDongminYoo/warm_alarm/issues

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.18.0-18.0.pre.54"

flutter:
  plugin:
    implements: warm_alarm
    platforms:
      ios:
        pluginClass: WarmAlarmPlugin
        dartPluginClass: WarmAlarmIOS

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  warm_alarm_platform_interface: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  pigeon: ^26.3.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.2.0
