// Copyright (c) 2026, Com andrew alarm
// dart format off
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum WarmAlarmSupportStatusWire: Int, CaseIterable {
  case supported = 0
  case limited = 1
  case unsupported = 2
  case unknown = 3
}

enum WarmAlarmReadinessLevelWire: Int, CaseIterable {
  case ready = 0
  case limited = 1
  case blocked = 2
  case unsupported = 3
}

enum WarmAlarmReadinessReasonWire: Int, CaseIterable {
  case notificationPermissionDenied = 0
  case exactAlarmPermissionDenied = 1
  case fullScreenPermissionDenied = 2
  case backgroundExecutionLimited = 3
  case backgroundAudioLimited = 4
  case platformUnsupported = 5
  case batteryOptimizationMayDelay = 6
  case unknown = 7
}

enum WarmAlarmNotificationAuthorizationStatusWire: Int, CaseIterable {
  case notDetermined = 0
  case denied = 1
  case authorized = 2
  case provisional = 3
  case ephemeral = 4
  case unknown = 5
}

enum WarmAlarmRemediationStatusWire: Int, CaseIterable {
  case completed = 0
  case unavailable = 1
  case unsupported = 2
}

enum WarmAlarmFailureCodeWire: Int, CaseIterable {
  case unknown = 0
  case invalidArguments = 1
  case permissionDenied = 2
  case exactAlarmUnavailable = 3
  case notificationUnavailable = 4
  case audioFileNotFound = 5
  case audioPlaybackFailed = 6
  case schedulingFailed = 7
  case platformInternalError = 8
}

enum WarmAlarmEventTypeWire: Int, CaseIterable {
  case scheduled = 0
  case fired = 1
  case stopped = 2
  case snoozed = 3
  case failed = 4
}

enum WarmAlarmLiveActivityStatusWire: Int, CaseIterable {
  case scheduled = 0
  case ringing = 1
  case snoozed = 2
}

enum WarmAlarmLiveActivityResultStatusWire: Int, CaseIterable {
  case completed = 0
  case unsupported = 1
  case disabled = 2
  case notFound = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmCapabilitiesWire: Hashable, CustomStringConvertible {
  var exactScheduling: WarmAlarmSupportStatusWire
  var notificationScheduling: WarmAlarmSupportStatusWire
  var backgroundAudioPlayback: WarmAlarmSupportStatusWire
  var fullScreenPresentation: WarmAlarmSupportStatusWire
  var wakeCheck: WarmAlarmSupportStatusWire
  var liveActivity: WarmAlarmSupportStatusWire


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmCapabilitiesWire? {
    let exactScheduling = pigeonVar_list[0] as! WarmAlarmSupportStatusWire
    let notificationScheduling = pigeonVar_list[1] as! WarmAlarmSupportStatusWire
    let backgroundAudioPlayback = pigeonVar_list[2] as! WarmAlarmSupportStatusWire
    let fullScreenPresentation = pigeonVar_list[3] as! WarmAlarmSupportStatusWire
    let wakeCheck = pigeonVar_list[4] as! WarmAlarmSupportStatusWire
    let liveActivity = pigeonVar_list[5] as! WarmAlarmSupportStatusWire

    return WarmAlarmCapabilitiesWire(
      exactScheduling: exactScheduling,
      notificationScheduling: notificationScheduling,
      backgroundAudioPlayback: backgroundAudioPlayback,
      fullScreenPresentation: fullScreenPresentation,
      wakeCheck: wakeCheck,
      liveActivity: liveActivity
    )
  }
  func toList() -> [Any?] {
    return [
      exactScheduling,
      notificationScheduling,
      backgroundAudioPlayback,
      fullScreenPresentation,
      wakeCheck,
      liveActivity,
    ]
  }
  static func == (lhs: WarmAlarmCapabilitiesWire, rhs: WarmAlarmCapabilitiesWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.exactScheduling, rhs.exactScheduling) && MessagesPigeonInternal.deepEquals(lhs.notificationScheduling, rhs.notificationScheduling) && MessagesPigeonInternal.deepEquals(lhs.backgroundAudioPlayback, rhs.backgroundAudioPlayback) && MessagesPigeonInternal.deepEquals(lhs.fullScreenPresentation, rhs.fullScreenPresentation) && MessagesPigeonInternal.deepEquals(lhs.wakeCheck, rhs.wakeCheck) && MessagesPigeonInternal.deepEquals(lhs.liveActivity, rhs.liveActivity)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmCapabilitiesWire")
    MessagesPigeonInternal.deepHash(value: exactScheduling, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notificationScheduling, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: backgroundAudioPlayback, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fullScreenPresentation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: wakeCheck, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: liveActivity, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmCapabilitiesWire(exactScheduling: \(String(describing: exactScheduling)), notificationScheduling: \(String(describing: notificationScheduling)), backgroundAudioPlayback: \(String(describing: backgroundAudioPlayback)), fullScreenPresentation: \(String(describing: fullScreenPresentation)), wakeCheck: \(String(describing: wakeCheck)), liveActivity: \(String(describing: liveActivity)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmPermissionStateWire: Hashable, CustomStringConvertible {
  var notificationsGranted: Bool
  var exactAlarmGranted: Bool
  var fullScreenIntentGranted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmPermissionStateWire? {
    let notificationsGranted = pigeonVar_list[0] as! Bool
    let exactAlarmGranted = pigeonVar_list[1] as! Bool
    let fullScreenIntentGranted = pigeonVar_list[2] as! Bool

    return WarmAlarmPermissionStateWire(
      notificationsGranted: notificationsGranted,
      exactAlarmGranted: exactAlarmGranted,
      fullScreenIntentGranted: fullScreenIntentGranted
    )
  }
  func toList() -> [Any?] {
    return [
      notificationsGranted,
      exactAlarmGranted,
      fullScreenIntentGranted,
    ]
  }
  static func == (lhs: WarmAlarmPermissionStateWire, rhs: WarmAlarmPermissionStateWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.notificationsGranted, rhs.notificationsGranted) && MessagesPigeonInternal.deepEquals(lhs.exactAlarmGranted, rhs.exactAlarmGranted) && MessagesPigeonInternal.deepEquals(lhs.fullScreenIntentGranted, rhs.fullScreenIntentGranted)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmPermissionStateWire")
    MessagesPigeonInternal.deepHash(value: notificationsGranted, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: exactAlarmGranted, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fullScreenIntentGranted, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmPermissionStateWire(notificationsGranted: \(String(describing: notificationsGranted)), exactAlarmGranted: \(String(describing: exactAlarmGranted)), fullScreenIntentGranted: \(String(describing: fullScreenIntentGranted)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmNotificationSettingsWire: Hashable, CustomStringConvertible {
  var authorizationStatus: WarmAlarmNotificationAuthorizationStatusWire
  var alertsEnabled: Bool
  var soundsEnabled: Bool
  var timeSensitiveEnabled: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmNotificationSettingsWire? {
    let authorizationStatus = pigeonVar_list[0] as! WarmAlarmNotificationAuthorizationStatusWire
    let alertsEnabled = pigeonVar_list[1] as! Bool
    let soundsEnabled = pigeonVar_list[2] as! Bool
    let timeSensitiveEnabled: Bool? = nilOrValue(pigeonVar_list[3])

    return WarmAlarmNotificationSettingsWire(
      authorizationStatus: authorizationStatus,
      alertsEnabled: alertsEnabled,
      soundsEnabled: soundsEnabled,
      timeSensitiveEnabled: timeSensitiveEnabled
    )
  }
  func toList() -> [Any?] {
    return [
      authorizationStatus,
      alertsEnabled,
      soundsEnabled,
      timeSensitiveEnabled,
    ]
  }
  static func == (lhs: WarmAlarmNotificationSettingsWire, rhs: WarmAlarmNotificationSettingsWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.authorizationStatus, rhs.authorizationStatus) && MessagesPigeonInternal.deepEquals(lhs.alertsEnabled, rhs.alertsEnabled) && MessagesPigeonInternal.deepEquals(lhs.soundsEnabled, rhs.soundsEnabled) && MessagesPigeonInternal.deepEquals(lhs.timeSensitiveEnabled, rhs.timeSensitiveEnabled)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmNotificationSettingsWire")
    MessagesPigeonInternal.deepHash(value: authorizationStatus, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: alertsEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: soundsEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timeSensitiveEnabled, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmNotificationSettingsWire(authorizationStatus: \(String(describing: authorizationStatus)), alertsEnabled: \(String(describing: alertsEnabled)), soundsEnabled: \(String(describing: soundsEnabled)), timeSensitiveEnabled: \(String(describing: timeSensitiveEnabled)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmReadinessWire: Hashable, CustomStringConvertible {
  var level: WarmAlarmReadinessLevelWire
  var reasons: [WarmAlarmReadinessReasonWire]
  var notificationSettings: WarmAlarmNotificationSettingsWire? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmReadinessWire? {
    let level = pigeonVar_list[0] as! WarmAlarmReadinessLevelWire
    let reasons = pigeonVar_list[1] as! [WarmAlarmReadinessReasonWire]
    let notificationSettings: WarmAlarmNotificationSettingsWire? = nilOrValue(pigeonVar_list[2])

    return WarmAlarmReadinessWire(
      level: level,
      reasons: reasons,
      notificationSettings: notificationSettings
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      reasons,
      notificationSettings,
    ]
  }
  static func == (lhs: WarmAlarmReadinessWire, rhs: WarmAlarmReadinessWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.level, rhs.level) && MessagesPigeonInternal.deepEquals(lhs.reasons, rhs.reasons) && MessagesPigeonInternal.deepEquals(lhs.notificationSettings, rhs.notificationSettings)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmReadinessWire")
    MessagesPigeonInternal.deepHash(value: level, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reasons, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notificationSettings, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmReadinessWire(level: \(String(describing: level)), reasons: \(String(describing: reasons)), notificationSettings: \(String(describing: notificationSettings)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmRemediationResultWire: Hashable, CustomStringConvertible {
  var status: WarmAlarmRemediationStatusWire
  var permissionState: WarmAlarmPermissionStateWire
  var readiness: WarmAlarmReadinessWire


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmRemediationResultWire? {
    let status = pigeonVar_list[0] as! WarmAlarmRemediationStatusWire
    let permissionState = pigeonVar_list[1] as! WarmAlarmPermissionStateWire
    let readiness = pigeonVar_list[2] as! WarmAlarmReadinessWire

    return WarmAlarmRemediationResultWire(
      status: status,
      permissionState: permissionState,
      readiness: readiness
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      permissionState,
      readiness,
    ]
  }
  static func == (lhs: WarmAlarmRemediationResultWire, rhs: WarmAlarmRemediationResultWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.permissionState, rhs.permissionState) && MessagesPigeonInternal.deepEquals(lhs.readiness, rhs.readiness)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmRemediationResultWire")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: permissionState, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: readiness, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmRemediationResultWire(status: \(String(describing: status)), permissionState: \(String(describing: permissionState)), readiness: \(String(describing: readiness)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmWarningWire: Hashable, CustomStringConvertible {
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmWarningWire? {
    let message = pigeonVar_list[0] as! String

    return WarmAlarmWarningWire(
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      message
    ]
  }
  static func == (lhs: WarmAlarmWarningWire, rhs: WarmAlarmWarningWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmWarningWire")
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmWarningWire(message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmFailureWire: Hashable, CustomStringConvertible {
  var code: WarmAlarmFailureCodeWire
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmFailureWire? {
    let code = pigeonVar_list[0] as! WarmAlarmFailureCodeWire
    let message: String? = nilOrValue(pigeonVar_list[1])

    return WarmAlarmFailureWire(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: WarmAlarmFailureWire, rhs: WarmAlarmFailureWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmFailureWire")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmFailureWire(code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmScheduleResultWire: Hashable, CustomStringConvertible {
  var alarmId: Int64
  var readiness: WarmAlarmReadinessWire
  var warning: WarmAlarmWarningWire? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmScheduleResultWire? {
    let alarmId = pigeonVar_list[0] as! Int64
    let readiness = pigeonVar_list[1] as! WarmAlarmReadinessWire
    let warning: WarmAlarmWarningWire? = nilOrValue(pigeonVar_list[2])

    return WarmAlarmScheduleResultWire(
      alarmId: alarmId,
      readiness: readiness,
      warning: warning
    )
  }
  func toList() -> [Any?] {
    return [
      alarmId,
      readiness,
      warning,
    ]
  }
  static func == (lhs: WarmAlarmScheduleResultWire, rhs: WarmAlarmScheduleResultWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alarmId, rhs.alarmId) && MessagesPigeonInternal.deepEquals(lhs.readiness, rhs.readiness) && MessagesPigeonInternal.deepEquals(lhs.warning, rhs.warning)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmScheduleResultWire")
    MessagesPigeonInternal.deepHash(value: alarmId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: readiness, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: warning, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmScheduleResultWire(alarmId: \(String(describing: alarmId)), readiness: \(String(describing: readiness)), warning: \(String(describing: warning)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmNotificationWire: Hashable, CustomStringConvertible {
  var title: String
  var body: String
  var stopActionTitle: String? = nil
  var snoozeActionTitle: String? = nil
  var androidIcon: String? = nil
  var androidIconColor: Int64? = nil
  var keepNotificationAfterAlarmEnds: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmNotificationWire? {
    let title = pigeonVar_list[0] as! String
    let body = pigeonVar_list[1] as! String
    let stopActionTitle: String? = nilOrValue(pigeonVar_list[2])
    let snoozeActionTitle: String? = nilOrValue(pigeonVar_list[3])
    let androidIcon: String? = nilOrValue(pigeonVar_list[4])
    let androidIconColor: Int64? = nilOrValue(pigeonVar_list[5])
    let keepNotificationAfterAlarmEnds = pigeonVar_list[6] as! Bool

    return WarmAlarmNotificationWire(
      title: title,
      body: body,
      stopActionTitle: stopActionTitle,
      snoozeActionTitle: snoozeActionTitle,
      androidIcon: androidIcon,
      androidIconColor: androidIconColor,
      keepNotificationAfterAlarmEnds: keepNotificationAfterAlarmEnds
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      body,
      stopActionTitle,
      snoozeActionTitle,
      androidIcon,
      androidIconColor,
      keepNotificationAfterAlarmEnds,
    ]
  }
  static func == (lhs: WarmAlarmNotificationWire, rhs: WarmAlarmNotificationWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.body, rhs.body) && MessagesPigeonInternal.deepEquals(lhs.stopActionTitle, rhs.stopActionTitle) && MessagesPigeonInternal.deepEquals(lhs.snoozeActionTitle, rhs.snoozeActionTitle) && MessagesPigeonInternal.deepEquals(lhs.androidIcon, rhs.androidIcon) && MessagesPigeonInternal.deepEquals(lhs.androidIconColor, rhs.androidIconColor) && MessagesPigeonInternal.deepEquals(lhs.keepNotificationAfterAlarmEnds, rhs.keepNotificationAfterAlarmEnds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmNotificationWire")
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: body, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stopActionTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: snoozeActionTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: androidIcon, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: androidIconColor, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: keepNotificationAfterAlarmEnds, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmNotificationWire(title: \(String(describing: title)), body: \(String(describing: body)), stopActionTitle: \(String(describing: stopActionTitle)), snoozeActionTitle: \(String(describing: snoozeActionTitle)), androidIcon: \(String(describing: androidIcon)), androidIconColor: \(String(describing: androidIconColor)), keepNotificationAfterAlarmEnds: \(String(describing: keepNotificationAfterAlarmEnds)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmVolumeFadeStepWire: Hashable, CustomStringConvertible {
  var timeMillis: Int64
  var volume: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmVolumeFadeStepWire? {
    let timeMillis = pigeonVar_list[0] as! Int64
    let volume = pigeonVar_list[1] as! Double

    return WarmAlarmVolumeFadeStepWire(
      timeMillis: timeMillis,
      volume: volume
    )
  }
  func toList() -> [Any?] {
    return [
      timeMillis,
      volume,
    ]
  }
  static func == (lhs: WarmAlarmVolumeFadeStepWire, rhs: WarmAlarmVolumeFadeStepWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.timeMillis, rhs.timeMillis) && MessagesPigeonInternal.deepEquals(lhs.volume, rhs.volume)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmVolumeFadeStepWire")
    MessagesPigeonInternal.deepHash(value: timeMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: volume, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmVolumeFadeStepWire(timeMillis: \(String(describing: timeMillis)), volume: \(String(describing: volume)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmAudioWire: Hashable, CustomStringConvertible {
  var filePath: String? = nil
  var assetPath: String? = nil
  var loop: Bool
  var volume: Double? = nil
  var fadeInDurationMillis: Int64? = nil
  var vibrate: Bool
  var volumeEnforced: Bool
  var fadeSteps: [WarmAlarmVolumeFadeStepWire]? = nil
  var systemSoundFilePath: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmAudioWire? {
    let filePath: String? = nilOrValue(pigeonVar_list[0])
    let assetPath: String? = nilOrValue(pigeonVar_list[1])
    let loop = pigeonVar_list[2] as! Bool
    let volume: Double? = nilOrValue(pigeonVar_list[3])
    let fadeInDurationMillis: Int64? = nilOrValue(pigeonVar_list[4])
    let vibrate = pigeonVar_list[5] as! Bool
    let volumeEnforced = pigeonVar_list[6] as! Bool
    let fadeSteps: [WarmAlarmVolumeFadeStepWire]? = nilOrValue(pigeonVar_list[7])
    let systemSoundFilePath: String? = nilOrValue(pigeonVar_list[8])

    return WarmAlarmAudioWire(
      filePath: filePath,
      assetPath: assetPath,
      loop: loop,
      volume: volume,
      fadeInDurationMillis: fadeInDurationMillis,
      vibrate: vibrate,
      volumeEnforced: volumeEnforced,
      fadeSteps: fadeSteps,
      systemSoundFilePath: systemSoundFilePath
    )
  }
  func toList() -> [Any?] {
    return [
      filePath,
      assetPath,
      loop,
      volume,
      fadeInDurationMillis,
      vibrate,
      volumeEnforced,
      fadeSteps,
      systemSoundFilePath,
    ]
  }
  static func == (lhs: WarmAlarmAudioWire, rhs: WarmAlarmAudioWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.filePath, rhs.filePath) && MessagesPigeonInternal.deepEquals(lhs.assetPath, rhs.assetPath) && MessagesPigeonInternal.deepEquals(lhs.loop, rhs.loop) && MessagesPigeonInternal.deepEquals(lhs.volume, rhs.volume) && MessagesPigeonInternal.deepEquals(lhs.fadeInDurationMillis, rhs.fadeInDurationMillis) && MessagesPigeonInternal.deepEquals(lhs.vibrate, rhs.vibrate) && MessagesPigeonInternal.deepEquals(lhs.volumeEnforced, rhs.volumeEnforced) && MessagesPigeonInternal.deepEquals(lhs.fadeSteps, rhs.fadeSteps) && MessagesPigeonInternal.deepEquals(lhs.systemSoundFilePath, rhs.systemSoundFilePath)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmAudioWire")
    MessagesPigeonInternal.deepHash(value: filePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: assetPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: loop, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: volume, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fadeInDurationMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: vibrate, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: volumeEnforced, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fadeSteps, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: systemSoundFilePath, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmAudioWire(filePath: \(String(describing: filePath)), assetPath: \(String(describing: assetPath)), loop: \(String(describing: loop)), volume: \(String(describing: volume)), fadeInDurationMillis: \(String(describing: fadeInDurationMillis)), vibrate: \(String(describing: vibrate)), volumeEnforced: \(String(describing: volumeEnforced)), fadeSteps: \(String(describing: fadeSteps)), systemSoundFilePath: \(String(describing: systemSoundFilePath)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmRecurrenceWire: Hashable, CustomStringConvertible {
  var weekdays: [Int64]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmRecurrenceWire? {
    let weekdays = pigeonVar_list[0] as! [Int64]

    return WarmAlarmRecurrenceWire(
      weekdays: weekdays
    )
  }
  func toList() -> [Any?] {
    return [
      weekdays
    ]
  }
  static func == (lhs: WarmAlarmRecurrenceWire, rhs: WarmAlarmRecurrenceWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.weekdays, rhs.weekdays)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmRecurrenceWire")
    MessagesPigeonInternal.deepHash(value: weekdays, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmRecurrenceWire(weekdays: \(String(describing: weekdays)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmSnoozeWire: Hashable, CustomStringConvertible {
  var durationMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmSnoozeWire? {
    let durationMillis = pigeonVar_list[0] as! Int64

    return WarmAlarmSnoozeWire(
      durationMillis: durationMillis
    )
  }
  func toList() -> [Any?] {
    return [
      durationMillis
    ]
  }
  static func == (lhs: WarmAlarmSnoozeWire, rhs: WarmAlarmSnoozeWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.durationMillis, rhs.durationMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmSnoozeWire")
    MessagesPigeonInternal.deepHash(value: durationMillis, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmSnoozeWire(durationMillis: \(String(describing: durationMillis)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmScheduleWire: Hashable, CustomStringConvertible {
  var id: Int64
  var scheduledAtMillis: Int64
  var notification: WarmAlarmNotificationWire
  var audio: WarmAlarmAudioWire
  var recurrence: WarmAlarmRecurrenceWire? = nil
  var snooze: WarmAlarmSnoozeWire? = nil
  var payload: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmScheduleWire? {
    let id = pigeonVar_list[0] as! Int64
    let scheduledAtMillis = pigeonVar_list[1] as! Int64
    let notification = pigeonVar_list[2] as! WarmAlarmNotificationWire
    let audio = pigeonVar_list[3] as! WarmAlarmAudioWire
    let recurrence: WarmAlarmRecurrenceWire? = nilOrValue(pigeonVar_list[4])
    let snooze: WarmAlarmSnoozeWire? = nilOrValue(pigeonVar_list[5])
    let payload: String? = nilOrValue(pigeonVar_list[6])

    return WarmAlarmScheduleWire(
      id: id,
      scheduledAtMillis: scheduledAtMillis,
      notification: notification,
      audio: audio,
      recurrence: recurrence,
      snooze: snooze,
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      scheduledAtMillis,
      notification,
      audio,
      recurrence,
      snooze,
      payload,
    ]
  }
  static func == (lhs: WarmAlarmScheduleWire, rhs: WarmAlarmScheduleWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.scheduledAtMillis, rhs.scheduledAtMillis) && MessagesPigeonInternal.deepEquals(lhs.notification, rhs.notification) && MessagesPigeonInternal.deepEquals(lhs.audio, rhs.audio) && MessagesPigeonInternal.deepEquals(lhs.recurrence, rhs.recurrence) && MessagesPigeonInternal.deepEquals(lhs.snooze, rhs.snooze) && MessagesPigeonInternal.deepEquals(lhs.payload, rhs.payload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmScheduleWire")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scheduledAtMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notification, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: recurrence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: snooze, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: payload, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmScheduleWire(id: \(String(describing: id)), scheduledAtMillis: \(String(describing: scheduledAtMillis)), notification: \(String(describing: notification)), audio: \(String(describing: audio)), recurrence: \(String(describing: recurrence)), snooze: \(String(describing: snooze)), payload: \(String(describing: payload)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmSnapshotWire: Hashable, CustomStringConvertible {
  var id: Int64
  var scheduledAtMillis: Int64
  var notification: WarmAlarmNotificationWire
  var audio: WarmAlarmAudioWire
  var recurrence: WarmAlarmRecurrenceWire? = nil
  var snooze: WarmAlarmSnoozeWire? = nil
  var payload: String? = nil
  var systemManagedAudio: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmSnapshotWire? {
    let id = pigeonVar_list[0] as! Int64
    let scheduledAtMillis = pigeonVar_list[1] as! Int64
    let notification = pigeonVar_list[2] as! WarmAlarmNotificationWire
    let audio = pigeonVar_list[3] as! WarmAlarmAudioWire
    let recurrence: WarmAlarmRecurrenceWire? = nilOrValue(pigeonVar_list[4])
    let snooze: WarmAlarmSnoozeWire? = nilOrValue(pigeonVar_list[5])
    let payload: String? = nilOrValue(pigeonVar_list[6])
    let systemManagedAudio: Bool? = nilOrValue(pigeonVar_list[7])

    return WarmAlarmSnapshotWire(
      id: id,
      scheduledAtMillis: scheduledAtMillis,
      notification: notification,
      audio: audio,
      recurrence: recurrence,
      snooze: snooze,
      payload: payload,
      systemManagedAudio: systemManagedAudio
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      scheduledAtMillis,
      notification,
      audio,
      recurrence,
      snooze,
      payload,
      systemManagedAudio,
    ]
  }
  static func == (lhs: WarmAlarmSnapshotWire, rhs: WarmAlarmSnapshotWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.scheduledAtMillis, rhs.scheduledAtMillis) && MessagesPigeonInternal.deepEquals(lhs.notification, rhs.notification) && MessagesPigeonInternal.deepEquals(lhs.audio, rhs.audio) && MessagesPigeonInternal.deepEquals(lhs.recurrence, rhs.recurrence) && MessagesPigeonInternal.deepEquals(lhs.snooze, rhs.snooze) && MessagesPigeonInternal.deepEquals(lhs.payload, rhs.payload) && MessagesPigeonInternal.deepEquals(lhs.systemManagedAudio, rhs.systemManagedAudio)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmSnapshotWire")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scheduledAtMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: notification, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: audio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: recurrence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: snooze, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: payload, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: systemManagedAudio, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmSnapshotWire(id: \(String(describing: id)), scheduledAtMillis: \(String(describing: scheduledAtMillis)), notification: \(String(describing: notification)), audio: \(String(describing: audio)), recurrence: \(String(describing: recurrence)), snooze: \(String(describing: snooze)), payload: \(String(describing: payload)), systemManagedAudio: \(String(describing: systemManagedAudio)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmEventWire: Hashable, CustomStringConvertible {
  var alarmId: Int64
  var type: WarmAlarmEventTypeWire
  var occurredAtMillis: Int64
  var snoozeDurationMillis: Int64? = nil
  var failure: WarmAlarmFailureWire? = nil
  var payload: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmEventWire? {
    let alarmId = pigeonVar_list[0] as! Int64
    let type = pigeonVar_list[1] as! WarmAlarmEventTypeWire
    let occurredAtMillis = pigeonVar_list[2] as! Int64
    let snoozeDurationMillis: Int64? = nilOrValue(pigeonVar_list[3])
    let failure: WarmAlarmFailureWire? = nilOrValue(pigeonVar_list[4])
    let payload: String? = nilOrValue(pigeonVar_list[5])

    return WarmAlarmEventWire(
      alarmId: alarmId,
      type: type,
      occurredAtMillis: occurredAtMillis,
      snoozeDurationMillis: snoozeDurationMillis,
      failure: failure,
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      alarmId,
      type,
      occurredAtMillis,
      snoozeDurationMillis,
      failure,
      payload,
    ]
  }
  static func == (lhs: WarmAlarmEventWire, rhs: WarmAlarmEventWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alarmId, rhs.alarmId) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.occurredAtMillis, rhs.occurredAtMillis) && MessagesPigeonInternal.deepEquals(lhs.snoozeDurationMillis, rhs.snoozeDurationMillis) && MessagesPigeonInternal.deepEquals(lhs.failure, rhs.failure) && MessagesPigeonInternal.deepEquals(lhs.payload, rhs.payload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmEventWire")
    MessagesPigeonInternal.deepHash(value: alarmId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: occurredAtMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: snoozeDurationMillis, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: failure, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: payload, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmEventWire(alarmId: \(String(describing: alarmId)), type: \(String(describing: type)), occurredAtMillis: \(String(describing: occurredAtMillis)), snoozeDurationMillis: \(String(describing: snoozeDurationMillis)), failure: \(String(describing: failure)), payload: \(String(describing: payload)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmLiveActivityStateWire: Hashable, CustomStringConvertible {
  var alarmId: Int64
  var title: String
  var status: WarmAlarmLiveActivityStatusWire
  var scheduledAtMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmLiveActivityStateWire? {
    let alarmId = pigeonVar_list[0] as! Int64
    let title = pigeonVar_list[1] as! String
    let status = pigeonVar_list[2] as! WarmAlarmLiveActivityStatusWire
    let scheduledAtMillis: Int64? = nilOrValue(pigeonVar_list[3])

    return WarmAlarmLiveActivityStateWire(
      alarmId: alarmId,
      title: title,
      status: status,
      scheduledAtMillis: scheduledAtMillis
    )
  }
  func toList() -> [Any?] {
    return [
      alarmId,
      title,
      status,
      scheduledAtMillis,
    ]
  }
  static func == (lhs: WarmAlarmLiveActivityStateWire, rhs: WarmAlarmLiveActivityStateWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alarmId, rhs.alarmId) && MessagesPigeonInternal.deepEquals(lhs.title, rhs.title) && MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.scheduledAtMillis, rhs.scheduledAtMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmLiveActivityStateWire")
    MessagesPigeonInternal.deepHash(value: alarmId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: title, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: scheduledAtMillis, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmLiveActivityStateWire(alarmId: \(String(describing: alarmId)), title: \(String(describing: title)), status: \(String(describing: status)), scheduledAtMillis: \(String(describing: scheduledAtMillis)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WarmAlarmLiveActivityResultWire: Hashable, CustomStringConvertible {
  var status: WarmAlarmLiveActivityResultStatusWire
  var activityId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WarmAlarmLiveActivityResultWire? {
    let status = pigeonVar_list[0] as! WarmAlarmLiveActivityResultStatusWire
    let activityId: String? = nilOrValue(pigeonVar_list[1])

    return WarmAlarmLiveActivityResultWire(
      status: status,
      activityId: activityId
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      activityId,
    ]
  }
  static func == (lhs: WarmAlarmLiveActivityResultWire, rhs: WarmAlarmLiveActivityResultWire) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.activityId, rhs.activityId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WarmAlarmLiveActivityResultWire")
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: activityId, hasher: &hasher)
  }

  public var description: String {
    return "WarmAlarmLiveActivityResultWire(status: \(String(describing: status)), activityId: \(String(describing: activityId)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmSupportStatusWire(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmReadinessLevelWire(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmReadinessReasonWire(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmNotificationAuthorizationStatusWire(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmRemediationStatusWire(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmFailureCodeWire(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmEventTypeWire(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmLiveActivityStatusWire(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WarmAlarmLiveActivityResultStatusWire(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      return WarmAlarmCapabilitiesWire.fromList(self.readValue() as! [Any?])
    case 139:
      return WarmAlarmPermissionStateWire.fromList(self.readValue() as! [Any?])
    case 140:
      return WarmAlarmNotificationSettingsWire.fromList(self.readValue() as! [Any?])
    case 141:
      return WarmAlarmReadinessWire.fromList(self.readValue() as! [Any?])
    case 142:
      return WarmAlarmRemediationResultWire.fromList(self.readValue() as! [Any?])
    case 143:
      return WarmAlarmWarningWire.fromList(self.readValue() as! [Any?])
    case 144:
      return WarmAlarmFailureWire.fromList(self.readValue() as! [Any?])
    case 145:
      return WarmAlarmScheduleResultWire.fromList(self.readValue() as! [Any?])
    case 146:
      return WarmAlarmNotificationWire.fromList(self.readValue() as! [Any?])
    case 147:
      return WarmAlarmVolumeFadeStepWire.fromList(self.readValue() as! [Any?])
    case 148:
      return WarmAlarmAudioWire.fromList(self.readValue() as! [Any?])
    case 149:
      return WarmAlarmRecurrenceWire.fromList(self.readValue() as! [Any?])
    case 150:
      return WarmAlarmSnoozeWire.fromList(self.readValue() as! [Any?])
    case 151:
      return WarmAlarmScheduleWire.fromList(self.readValue() as! [Any?])
    case 152:
      return WarmAlarmSnapshotWire.fromList(self.readValue() as! [Any?])
    case 153:
      return WarmAlarmEventWire.fromList(self.readValue() as! [Any?])
    case 154:
      return WarmAlarmLiveActivityStateWire.fromList(self.readValue() as! [Any?])
    case 155:
      return WarmAlarmLiveActivityResultWire.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WarmAlarmSupportStatusWire {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmReadinessLevelWire {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmReadinessReasonWire {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmNotificationAuthorizationStatusWire {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmRemediationStatusWire {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmFailureCodeWire {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmEventTypeWire {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmLiveActivityStatusWire {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmLiveActivityResultStatusWire {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? WarmAlarmCapabilitiesWire {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmPermissionStateWire {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmNotificationSettingsWire {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmReadinessWire {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmRemediationResultWire {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmWarningWire {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmFailureWire {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmScheduleResultWire {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmNotificationWire {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmVolumeFadeStepWire {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmAudioWire {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmRecurrenceWire {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmSnoozeWire {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmScheduleWire {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmSnapshotWire {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmEventWire {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmLiveActivityStateWire {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? WarmAlarmLiveActivityResultWire {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WarmAlarmApi {
  func initialize(completion: @escaping (Result<Void, Error>) -> Void)
  func getCapabilities(completion: @escaping (Result<WarmAlarmCapabilitiesWire, Error>) -> Void)
  func getPermissionState(completion: @escaping (Result<WarmAlarmPermissionStateWire, Error>) -> Void)
  func getReadiness(completion: @escaping (Result<WarmAlarmReadinessWire, Error>) -> Void)
  func requestNotificationPermission(completion: @escaping (Result<WarmAlarmRemediationResultWire, Error>) -> Void)
  func openReadinessSettings(reason: WarmAlarmReadinessReasonWire, completion: @escaping (Result<WarmAlarmRemediationResultWire, Error>) -> Void)
  func scheduleAlarm(schedule: WarmAlarmScheduleWire, completion: @escaping (Result<WarmAlarmScheduleResultWire, Error>) -> Void)
  func prepareSystemSound(primaryFilePath: String, backgroundAssetPath: String?, completion: @escaping (Result<String?, Error>) -> Void)
  func cancelAlarm(id: Int64, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelAllAlarms(completion: @escaping (Result<Void, Error>) -> Void)
  func getScheduledAlarms(completion: @escaping (Result<[WarmAlarmSnapshotWire], Error>) -> Void)
  func isRinging(alarmId: Int64?, completion: @escaping (Result<Bool, Error>) -> Void)
  func setKillWarning(title: String, body: String, completion: @escaping (Result<Void, Error>) -> Void)
  func clearKillWarning(completion: @escaping (Result<Void, Error>) -> Void)
  func startLiveActivity(state: WarmAlarmLiveActivityStateWire, completion: @escaping (Result<WarmAlarmLiveActivityResultWire, Error>) -> Void)
  func updateLiveActivity(activityId: String, state: WarmAlarmLiveActivityStateWire, completion: @escaping (Result<WarmAlarmLiveActivityResultWire, Error>) -> Void)
  func endLiveActivity(activityId: String, completion: @escaping (Result<WarmAlarmLiveActivityResultWire, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WarmAlarmApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WarmAlarmApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WarmAlarmApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        api.initialize { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        api.getCapabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let getPermissionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.getPermissionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPermissionStateChannel.setMessageHandler { _, reply in
        api.getPermissionState { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPermissionStateChannel.setMessageHandler(nil)
    }
    let getReadinessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.getReadiness\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getReadinessChannel.setMessageHandler { _, reply in
        api.getReadiness { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getReadinessChannel.setMessageHandler(nil)
    }
    let requestNotificationPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.requestNotificationPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestNotificationPermissionChannel.setMessageHandler { _, reply in
        api.requestNotificationPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestNotificationPermissionChannel.setMessageHandler(nil)
    }
    let openReadinessSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.openReadinessSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openReadinessSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reasonArg = args[0] as! WarmAlarmReadinessReasonWire
        api.openReadinessSettings(reason: reasonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openReadinessSettingsChannel.setMessageHandler(nil)
    }
    let scheduleAlarmChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.scheduleAlarm\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scheduleAlarmChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let scheduleArg = args[0] as! WarmAlarmScheduleWire
        api.scheduleAlarm(schedule: scheduleArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scheduleAlarmChannel.setMessageHandler(nil)
    }
    let prepareSystemSoundChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.prepareSystemSound\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareSystemSoundChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let primaryFilePathArg = args[0] as! String
        let backgroundAssetPathArg: String? = nilOrValue(args[1])
        api.prepareSystemSound(primaryFilePath: primaryFilePathArg, backgroundAssetPath: backgroundAssetPathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareSystemSoundChannel.setMessageHandler(nil)
    }
    let cancelAlarmChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.cancelAlarm\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAlarmChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        api.cancelAlarm(id: idArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAlarmChannel.setMessageHandler(nil)
    }
    let cancelAllAlarmsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.cancelAllAlarms\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelAllAlarmsChannel.setMessageHandler { _, reply in
        api.cancelAllAlarms { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelAllAlarmsChannel.setMessageHandler(nil)
    }
    let getScheduledAlarmsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.getScheduledAlarms\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getScheduledAlarmsChannel.setMessageHandler { _, reply in
        api.getScheduledAlarms { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getScheduledAlarmsChannel.setMessageHandler(nil)
    }
    let isRingingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.isRinging\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isRingingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alarmIdArg: Int64? = nilOrValue(args[0])
        api.isRinging(alarmId: alarmIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isRingingChannel.setMessageHandler(nil)
    }
    let setKillWarningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.setKillWarning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setKillWarningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        let bodyArg = args[1] as! String
        api.setKillWarning(title: titleArg, body: bodyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setKillWarningChannel.setMessageHandler(nil)
    }
    let clearKillWarningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.clearKillWarning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearKillWarningChannel.setMessageHandler { _, reply in
        api.clearKillWarning { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearKillWarningChannel.setMessageHandler(nil)
    }
    let startLiveActivityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.startLiveActivity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startLiveActivityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let stateArg = args[0] as! WarmAlarmLiveActivityStateWire
        api.startLiveActivity(state: stateArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startLiveActivityChannel.setMessageHandler(nil)
    }
    let updateLiveActivityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.updateLiveActivity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateLiveActivityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let activityIdArg = args[0] as! String
        let stateArg = args[1] as! WarmAlarmLiveActivityStateWire
        api.updateLiveActivity(activityId: activityIdArg, state: stateArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateLiveActivityChannel.setMessageHandler(nil)
    }
    let endLiveActivityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.warm_alarm.WarmAlarmApi.endLiveActivity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endLiveActivityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let activityIdArg = args[0] as! String
        api.endLiveActivity(activityId: activityIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      endLiveActivityChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol WarmAlarmEventsApiProtocol {
  func emitEvent(event eventArg: WarmAlarmEventWire, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class WarmAlarmEventsApi: WarmAlarmEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func emitEvent(event eventArg: WarmAlarmEventWire, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.warm_alarm.WarmAlarmEventsApi.emitEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
