version: "0.2"
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
import:
  - https://raw.githubusercontent.com/AndrewDongminYoo/quality-configs/v0.8.0/configs/cspell.config.yaml
  - https://raw.githubusercontent.com/AndrewDongminYoo/quality-configs/v0.8.0/configs/cspell/vgv.config.yaml
dictionaries:
  - en-gb
  - custom-dictionary
  - flutter
  - dart
  - cpp
  - cpp-legacy
  - cpp-compound-words
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
useGitignore: true
ignorePaths:
  - .github/workflows/**
  - .gitignore
  - "**/project.pbxproj"
  - "**/Runner.xcscheme"
  - "**/MainMenu.xib"
ignoreWords:
  - datatype
  - plaintext
words:
  - Dongmin
  - fluttium
  - WarmWake
