import 'dart:io';

/// Normalizes generator whitespace without changing the generated wire contract.
void main(List<String> arguments) {
  if (arguments.length != 1 || arguments.single != 'lib/src/messages.g.dart') {
    throw ArgumentError('Expected the platform package output: lib/src/messages.g.dart');
  }
  final file = File(arguments.single);
  final source = file.readAsStringSync();
  if (!source.contains('Autogenerated from Pigeon')) {
    throw StateError('Refusing to normalize a file without the Pigeon generation header.');
  }
  file.writeAsStringSync(source.replaceAll(RegExp(r'[ \t]+$', multiLine: true), ''));
}
