name: warm_alarm_platform_interface

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - .github/workflows/warm_alarm_platform_interface.yaml
      - warm_alarm_platform_interface/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/warm_alarm_platform_interface.yaml
      - warm_alarm_platform_interface/**

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@61d25935870f12a1f2c23f2a04d5f193c83f4e5d # v1.21.1
    with:
      coverage_excludes: "**/*.g.dart"
      format_line_length: 120
      working_directory: warm_alarm_platform_interface

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@61d25935870f12a1f2c23f2a04d5f193c83f4e5d # v1.21.1
    with:
      working_directory: warm_alarm_platform_interface
