name: warm_alarm_macos

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - .github/workflows/warm_alarm_macos.yaml
      - warm_alarm_macos/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/warm_alarm_macos.yaml
      - warm_alarm_macos/**

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.41.1
      working_directory: warm_alarm_macos

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
